name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deps
        run: python3 -m pip install -r ${{github.workspace}}/requirements.txt
      - name: build
        run: python3 ${{github.workspace}}/build.py ${{secrets.NEKOWEB_API_KEY}}
